### ISSUE TITLE
startPriceDate, endPriceDate?

### ISSUE THREAD

**Issue by laurensormskerk** [fruitl00p/php-mt940#20]
Hey fruitl00p, I was wondering if you could add the possibility to get a startPriceDate and an endPriceDate out of a mt940-file to your library? Thanks in advance!

**Comment by fruitl00p** [comment]
Sounds like you're looking for the statement timestamp... ? If not you may have to filter the transactions per statement and filter out max|min (value|entry)timestamps depending on which you want... ?

For this you might want something as explained here: http://stackoverflow.com/q/5166550/237750
(array_reduce the ```$statement->getTransactions()```)

For now I don't have any plans of adding getters for the lowest and highest (value|entry)timestamps, but if you really want it it might be something like
```php
class Statement {
/// ... 
    /**
     * @param string $which value|entry
     * @return int
     */
    public function getStartTimestamp($which = 'value') {
        $which = ($which === 'value') ? 'value' :  'entry';
        $transaction = $this->getTransactionTimestamp($which, 'min');
        if ($transaction === null) {
            return 0;
        }
        return $transaction->{'get'.$which.'Timestamp'}();
    }

    /**
     * @param string $which value|entry
     * @return int
     */
    public function getEndTimestamp($which = 'value') {
        $which = ($which === 'value') ? 'value' :  'entry';
        $transaction = $this->getTransactionTimestamp($which, 'max');
        if ($transaction === null) {
            return 0;
        }
        return $transaction->{'get'.$which.'Timestamp'}();
    }

    /**
     * @param string $which value|entry
     * @param string $spectrum min|max
     * @return Transaction|null
     */
    private function getTransactionTimestamp($which = 'value', $spectrum = 'max') {
        $transactions = $this->getTransactions();
        $initialValue = null;
        if ($spectrum === 'min') {
            $initialValue = array_shift($transactions);
        }
        return array_reduce($transactions, function($a, $b) use ($spectrum) {
            return ($a['value'] < $b['value'] && $spectrum === 'min') ? $a : $b;
        }, $initialValue);
    }
```

This is totally untested, so you might want to take a second look at the code above :)
(i didn't even try to run the code above)

**Comment by laurensormskerk** [comment]
Thanks for taking the effort and write that code for me! However, I actually thought this would be much easier. Watching some mt940-files, I think you can find that particular information in the beginning and in the end of the file. To be precise, almost at the top, in the 60F-tag and almost at the end in either one of the 62F-, 64- or 65-tags. I looked in one of the files I got and there it looks something like this:

```
:60F:C150731EUR164,92
```
and
```
:62F:C150904EUR623,65
:64:C150904EUR623,65
:65:C150905EUR623,65
:65:C150906EUR623,65
```
Where '150904' would be september 4th, 2015. You would say these are the dates for which period you exported the transactions, which I actually need. So, the last date for instance will then not always be necessary identical to the date of the last transaction.

Of course, I'm prepared the send you whatever example file you need to implement this if it's indeed this simple. And I'm sorry I wasn't clearer in my first post.

**Comment by fruitl00p** [comment]
The point is that the data is already parsed from the transactions ... thus the data is already there in the Transaction object... ? Reparsing the file would be silly :)

**Comment by laurensormskerk** [comment]
Hm, I now see you already take the time tied to the `$startPrice` from the 60F-tag. I'm going to use that one. However, getting the `$startPriceDate` or `$endPriceDate` by looking to the transactions is a total different thing. Imagine a statement with transactions from september the 1st to the 30th with the last transaction dated sept 25th. Then you wouldn't get the right `$endPriceDate`, because looking at the transactions you would get sept 25th, but looking at the date tied to the 62F-tag you would get sept 30th. Its important to have the right `$endPriceDate` for instances like mine where you want to make an importprogram where statements should not overlap but where there also should be no space between them.

I believe it would be more correct to change `$timestamp` in `$startPriceDate` and in addition offer an `$endPriceDate` as well. Have you ever looked into the other MT940-repositorie, the one from sandermarechal? He does it this way.

Wouldn't it be btw not much simpler to get the dates from the tags instead of using the code you supplied up here? I'm not that much of a hero in PHP so I wouldn't know.

**Comment by fruitl00p** [comment]
So what you're looking for is not the first and last date of the transactions of a statement, but the a possibly different date set: that of the statement itself?

**Comment by laurensormskerk** [comment]
Exactly! But I already figured out that it probably won't be too hard to implement, even for a PHP newbe as I am, since it's just a matter of copying your `getTimestamp()` code and apply it to 62F-tag? ;)

**Comment by fruitl00p** [comment]
Yup, seems that way :)

And seems like a proper addition to the statement class. Will add something of this order to the statement.

**Comment by laurensormskerk** [comment]
Nice! :angel:

**Comment by fruitl00p** [comment]
@laurensormskerk i will / am sticking to the timestamp convention: its easier to work with a timestamp than a date... + its more in line with the other timestamp on transaction itself..

Could you take a look at PR #21 I've managed the transition with backwards compatibility in tact so that everyone and everything should work (and have the start/end timestamps for a statement...)

Please test it out and let me know.

**Comment by laurensormskerk** [comment]
I totally agree with you the methods should return a timestamp, what I meant was naming it something with 'price' because the returned timestamp is tied to the start/endprice. But I tested the new code with my files and it works like a charm!

**Comment by fruitl00p** [comment]
Just coming back to this: you're in agreement that we should go with PR #21 ?

**Comment by laurensormskerk** [comment]
Yeah, yeah, I totally am! Except maybe for the naming as stated before.

**Comment by fruitl00p** [comment]
@laurensormskerk I just merged the changes into master thereby closing #21 I did keep the startTimestamp / endTimestamp naming as this (imho) better suits the actual returned data.
