### ISSUE TITLE
Add interfaces

### ISSUE THREAD

**Issue by SamMousa** [fruitl00p/php-mt940#25]
There should be an interface for parsers instead of a base object.
The base parser could then implement the interface (partially or fully).
That would allow  external parsers to implement the interface in their own way.

**Comment by fruitl00p** [comment]
As this was mostly used internally I didn't see the need yet... but you're absolutely right! Feel free to do a PR or I will look into this upcoming Xmas weekend :)

**Comment by fruitl00p** [comment]
My bad, just noticed the pr #28 cool!
