### ISSUE TITLE
Transaction::getAccountName return type

### ISSUE THREAD

**Issue by SamMousa** [fruitl00p/php-mt940#26]
`Transaction::getAccountName()` should return `null` when no name is present in the transaction; returning an empty string is not the same.

**Comment by fruitl00p** [comment]
I feel that changing the return type would be worse than an empty string...

**Comment by SamMousa** [comment]
The point is that null in indicates a missing value while an empty string
is a valid name.

**Comment by fruitl00p** [comment]
I know blank is an invalid name, and as a setter it would be invalid, but the official mt940 docs (AFAIK) dont mention that a name has a minimum of characters, thus not switching return type has my preference... One might argue about throwing an exception, but thats a different story ;)

**Comment by SamMousa** [comment]
If mt940 doc don't have a minimum length then blank is valid.. That is why
we need null. Note that null is not a different type; it is not a type at
all

**Comment by fruitl00p** [comment]
`null` is a special type indeed, thats true... Anyone else have an idea of switching return types ?

**Comment by fruitl00p** [comment]
I still stand by my original point of view that returning NULL in this situation is weird? The return type is a string (it might be empty) but it is / should always be a string...
