### ISSUE TITLE
Separate factory from base engine.

### ISSUE THREAD

**Issue by SamMousa** [fruitl00p/php-mt940#29]
Currently `Kingsquare\Parser\Banking\Mt940\Engine` is both a parser and a factory.

It would be cleaner to create a separate `ParserFactory` and separate the logic of registering / finding / creating parsers from the parsers themselves.

**Comment by fruitl00p** [comment]
True... and that's something that has come to mind previously... just have to figure out where to put it... this also goes IMHO for the engine detection itself... that might even move out of the parser into the same factory. .. ? What do you think?

**Comment by SamMousa** [comment]
Well, the current approach in master (ie iterating and calling `isApplicable` is definitely something that can be moved to the factory.
(Assuming that's what you mean by engine detection)

**Comment by fruitl00p** [comment]
Thats indeed what i mean....

I can imagine something like
```php
Mt940\Factory::FromString($mt940String)
Mt940\Factory::FromBankIdentifier($bankConstant) // one of the already introduced constants?
Mt940\Factory::FromEngine(\Kingsquare\Contracts\TransactionInterface $engine) // just to complement the usage
```
Something like that?

**Comment by fruitl00p** [comment]
@SamMousa is this still a request? It would something of a BC break and thus would require a new major version ... Do you think my previous example would suffice? How would you like to see the factory?

**Comment by SamMousa** [comment]
@fruitl00p I think the request is still valid, I personally no longer have interest in it.

**Comment by fruitl00p** [comment]
@SamMousa thanks for letting me know. I'll leave it as is then and not have a BC break due to moving it out...
