### ISSUE TITLE
KNAB - New structured file

### ISSUE THREAD

**Issue by robgeerts** [fruitl00p/php-mt940#37]
KNAB now ahs the ability to export to the old format and a new structured one.
The next transaction is an example of the new format:

:61:1604290429D96,84N105NONREF//B6D29PGWUM0RDZ4H :86:/TRTP/SEPA ACCEPTGIRO/IBAN/NL83ABNA0437015300/BIC/ABNANL2AXXX /NAME/ACHMEA SCHADEVERZEKERINGEN N.V./EREF/5002100023310160 /REMI/EERSTE MAAND, MAART VERZEKERING 5002100023 310160

It's not a big change (i think)... But are you able te create a fix for this?

**Comment by fruitl00p** [comment]
shouldn't be a problem, will look into it tonight when i get home ;)

**Comment by robgeerts** [comment]
Great! :)
If you need another example, I'm close to my computer tonight.
By the way, Is it possible to handle both formats?

**Comment by fruitl00p** [comment]
It should be possible yes ;) Rabobank has the same 'issue': structured (new) vs unstructured (old) mt940 formats...

**Comment by fruitl00p** [comment]
@robgeerts I've hacked it in locally so your example is handled correctly. But it leaves me wondering if there are more changes and additions in the new format aside from the contents of `:86`... I've contacted them and have hopes that they respond quickly..

I've pushed the branch and will create a PR to track progress :)

**Comment by robgeerts** [comment]
Great, this works pretty good already!
The next example isn't parsed correctly yet:

:61:1604290429D999,07N100NONREF//B6D29PGAA69RN554 :86:/TRTP/SEPA OVERBOEKING/BBAN/51598679/BIC/KNABNL2HXXX/NAME/MYCOMPANYNAME

According to your script, this is the description: 
/TRTP/SEPA OVERBOEKING/BBAN/51598679/BIC/KNABNL2HXXX/NAME/MYCOMPANYNAME

This is an internal transaction from one private account to another...

**Comment by fruitl00p** [comment]
Hmmm... what would be a logical description in that case? I havent heard back from knab yet..

**Comment by robgeerts** [comment]
An empty description ;)
I haven't filled in anything in this case, that's why there's no /REMI/-part I think

**Comment by Vinze** [comment]
Any updates regarding parsing the new structured file of KNAB? :)

**Comment by fruitl00p** [comment]
@Vinze i thought i had this covered already :)

I'll take a look tonight to try and clean the #38 and #40 that both seem to do KNAB stuff...

In regards to @robgeerts note: i still wonder if an empty description would be sufficient for further processing in many cases... ?

**Comment by Vinze** [comment]
@fruitl00p Hope I'm not annoying you, but any chance you could take look at this? :)

**Comment by fruitl00p** [comment]
@Vinze i've pushed an update this morning and will try to finish it up today and create a new release!

**Comment by fruitl00p** [comment]
This has been merged into release [1.3.0](https://github.com/fruitl00p/php-mt940/tree/1.3.0)!

**Comment by Vinze** [comment]
Awesome, thanks!
