### ISSUE TITLE
Can you modify your code

### ISSUE THREAD

**Issue by stephanwoerner** [fruitl00p/php-mt940#43]
I will use your programm in a symfony2 project but I have a unknown mt940 file and symfony stops every time by "trigger_error". My file starts at first line with :20: folowed by date of file formated like "ymd".
Please delete line 68 in Engine.php and fill Unknown.php whit folowing code:
<?php
namespace Kingsquare\Parser\Banking\Mt940\Engine;

use Kingsquare\Parser\Banking\Mt940\Engine;

/**
 * empty class for fallback purposes
 *
 * @package Kingsquare\Parser\Banking\Mt940\Engine
 * @author Kingsquare (source@kingsquare.nl)
 * @license http://opensource.org/licenses/MIT MIT
 */
class Unknown extends Engine
{
    /**
     * uses field 25 to gather accoutnumber
     * @return string accountnumber
     */
    protected function parseStatementAccount()
    {
        $results = [];
        if (preg_match('/:25:([\d\.\/\d]+)*/', $this->getCurrentStatementData(), $results)
            && !empty($results[1])
        ) {
            return $this->sanitizeAccount($results[1]);
        }

        // SEPA / IBAN
        if (preg_match('/:25:([A-Z0-9]{8}[\d\.]+)*/', $this->getCurrentStatementData(), $results)
            && !empty($results[1])
        ) {
            return $this->sanitizeAccount($results[1]);
        }

        return '';
    }

    /**
     * Overloaded: Sparkasse uses 62M and 62F
     * @inheritdoc
     */
    protected function parseStatementEndPrice()
    {
        $results = [];
        if (preg_match('/:62[FM]:.*EUR([\d,\.]+)*/', $this->getCurrentStatementData(), $results)
            && !empty($results[1])
        ) {
            return $this->sanitizePrice($results[1]);
        }

        return '';
    }

    /**
     * Overloaded: Sparkasse uses 60M and 60F
     * @inheritdoc
     */
    protected function parseStatementStartPrice()
    {
        $results = [];
        if (preg_match('/:60[FM]:.*EUR([\d,\.]+)*/', $this->getCurrentStatementData(), $results)
            && !empty($results[1])
        ) {
            return $this->sanitizePrice($results[1]);
        }

        return '';
    }
}

**Comment by stephanwoerner** [comment]
Forget it, I have figured out that I can set my own Engine.php as parameter in function parse.

**Comment by fruitl00p** [comment]
You're too quick, but indeed, that would've been my answer. Instead of the trigger error, i could change that to an Exception... (namespaced et al)

Any thoughts anyone?

**Comment by stephanwoerner** [comment]
It's nothing to do for you but I think it can by an advantage for other programmers if you explane how to use own parser classes. 
Thanks.
