### ISSUE TITLE
Can't parse file

### ISSUE THREAD

**Issue by AndriySvirin** [fruitl00p/php-mt940#45]
My file begins from:
STARTDISP
Why it unparsable by 2 days?

**Comment by fruitl00p** [comment]
@AndriySvirin I dont know of any mt940 file with this prefix? Does the 'unknown' engine somewhat parse it? or anything? Is there a spec available? You could try to emulate it by adding a custom engine and try running it through your file to see what it cán parse...

For which bank are you trying to parse it? (a quick google came up with 2 or 3 banks with this as a possible prefix)

**Comment by fruitl00p** [comment]
@AndriySvirin is this still an issue? Is there anything i can help you with? Otherwise i'll close the issue in a few days
