### ISSUE TITLE
Problem parsing ABN Amro mt940 'Dagafschrift'

### ISSUE THREAD

**Issue by pverdu** [fruitl00p/php-mt940#46]
Hi,

We're making an application where we read an ABN Amro mt940 file that contains multiple statements. Problem is that this file doesn't contain the :20: tag and therefor there aren't any statements when reading this type of file.
The file is downloaded straight from the ABN Amro website and looks like this:

```
ABNANL2A
940
ABNANL2A
:25:NL62ABNAXXXXXXX
:28:XXX/XX
:60F:C161111EURXXXXXX,XX
:61:1611141114CXXX,XXNXXXXXXXX
:86:/TRTP/SEPA OVERBOEKING/IBAN/NL37ABNAXXXXXXXX/BIC/ABNANL2A/NAME/
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
:61:1611141114CXXX,XXNXXXXXXXX
:86:/TRTP/SEPA OVERBOEKING/IBAN/NL54ABNAXXXXXXXX/BIC/ABNANL2A/NAME/
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
:61:1611141114CXXXX,XXNXXXXXXXX
:86:/TRTP/SEPA OVERBOEKING/IBAN/NL28ABNAXXXXXXXX/BIC/ABNANL2A/NAME/
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
:62F:C161114EURXXXXXX,XX
:64:C161114EURXXXXXX,XX
:65:C161115EURXXXXXX,XX
:65:C161116EURXXXXXX,XX
:65:C161117EURXXXXXX,XX
:65:C161118EURXXXXXX,XX
:65:C161119EUEXXXXXX,XX
:65:C161120EURXXXXXX,XX
-
```

The example above is repeated a couple of times in 1 file.
Do you have any information about this type of mt940 files or do you possibly have a solution so it's possible to read this type of mt940 file?

Thanks in advance

**Comment by fruitl00p** [comment]
@pverdu are you sure you have the correct format? All the specs I've seen mention that the :20-field is mandatory and should be included? (or has ABN AMRO updated their specs?)

You could alter you input file and enter a single `:20:ABN AMRO BANK NV` file and i'll look into the specs to see if this is an official possibility

**Comment by pverdu** [comment]
We believe we do have the correct format yes. We're adding the :20: tag ourselves for now. I'l close this issue since all specs say the :20: tag is mandatory like you mentioned.

Thanks
