### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by MrMoronIV** [fruitl00p/php-mt940#61]
A basic example would come in handy.

I've already been searching for an hour to how exactly use this class.

How do you iterate over the parsedStatement variable?
What functions are available to get information from found transactions?

Why is this nowhere documented?

**Comment by fruitl00p** [comment]
I've added on to the example. I assumed (wrong i guess) that the code was pretty self explainatory just from the interface the Statement / and each Transaction gave... ? Hope this helps!
