### ISSUE TITLE
getRelativePrice() missing

### ISSUE THREAD

**Issue by MrMoronIV** [fruitl00p/php-mt940#62]
AFter installation using composer as instructed the getRelativePrice function inside Transaction.php is missing.

Composer seems to be installing a different version as is shown on github?
Inside my composer.json: "kingsquare/php-mt940": "^1.4"

Also, why are we on fruitl00p instead of Kingsquare?

**Comment by MrMoronIV** [comment]
Actually, there's more missing, did I not install the latest version somehow by following the instructions?

**Comment by fruitl00p** [comment]
I haven't released a new version in a while. You could go with dev-master, but i understand that this might not be ideal / confusing.

I'll release a new version today :)

**Comment by fruitl00p** [comment]
@MrMoronIV I've just now released 1.5.0 which includes the latest and greatest ;) This should help with both the documentation/example as with the latest additions.

As for the naming of the package this is derived from my employer company and I haven't taken the trouble of moving the repo itself ;)
