### ISSUE TITLE
File and folder case

### ISSUE THREAD

**Issue by theFreakus** [fruitl00p/php-mt940#9]
All the src files and folders are lowercase. This might work on Mac and Windows where the fs is case-insensitive, but it doesn't work in Linux.

**Comment by fruitl00p** [comment]
We use it in production linux (ubuntu, redhat and centos) based systems and it works like it should? What am i missing here?

**Comment by theFreakus** [comment]
Ahhh, i see. Your autoload.php has a classmap. But it won't used by composer. The package composer.json has
"autoload": {
	"psr-0":{
	  "Kingsquare": ["src/", "test/"]
	}
  }

in it. Which means autoloading by PSR-0 rules.

It works for you because you require Kingsquare/autoload.php by yourself. But normally you would just require vendor/autoload.php, which aggregates all the packages' autoloading. Easiest fix would be to ucfirst all the files and folders and change you autoload.php to reflect that. Then it will work if you use composer's autoloading stuff too.

**Comment by fruitl00p** [comment]
The autoload.php is a leftover from pre-composer ;)

I've just updated the code in 0.9.0 to address this and make everything a bit more compliant. I also think packages should only support supported PHP versions and thus will drop 5.3 before the 1.0 release.. (will post a separate issue regarding the php version bump)
